import React, { useState, useEffect } from "react";
import { withAdminProtection } from "@/components/auth";
import AdminLayout from "@/components/AdminDashboard/AdminLayout";
import DashboardOverview from "@/components/AdminDashboard/DashboardOverview";
import UserManagement from "@/components/AdminDashboard/UserManagement/UserManagement";
import PaymentManagement from "@/components/AdminDashboard/PaymentManagement";
import FinancialOverview from "@/components/AdminDashboard/FinancialOverview";
import LessonManagement from "@/components/AdminDashboard/LessonManagement";
import styles from "@/styles/AdminDashboard.module.css";
import { ModalProvider } from "@/contexts/ModalContext";
import ModalContainer from "@/components/ModalContainer";
import {
  Student,
  Teacher,
  Group,
} from "@/components/AdminDashboard/UserManagement/types";

// Types are now imported from the centralized types.ts file
type Students = Student; // For backward compatibility

const AdminDashboard: React.FC = () => {
  const [studentData, setStudentData] = useState<Students[]>([
    {
      id: "1",
      name: "أحمد محمد",
      payedClasses: 10,
      nextPaymentDate: "2025-07-15",
      amountPaid: 1000,
      remainingClasses: 4,
      postponedClasses: 2,
      canceledClasses: 1,
      absentClasses: 3,
      attendedClasses: 6,
      rate: 10,
      phoneNumber: "01012345678",
      groupName: "مجموعة 1",
    },
    {
      id: "2",
      name: "سارة علي",
      payedClasses: 8,
      nextPaymentDate: "2025-07-20",
      amountPaid: 800,
      remainingClasses: 6,
      postponedClasses: 1,
      canceledClasses: 0,
      absentClasses: 1,
      attendedClasses: 7,
      rate: 8,
      phoneNumber: "01098765432",
      groupName: "مجموعة 2",
    },
    {
      id: "3",
      name: "خالد سمير",
      payedClasses: 12,
      nextPaymentDate: "2025-07-18",
      amountPaid: 1200,
      remainingClasses: 9,
      postponedClasses: 0,
      canceledClasses: 1,
      absentClasses: 2,
      attendedClasses: 3,
      rate: 6,
      phoneNumber: "01122334455",
      groupName: "مجموعة 1",
    },
    {
      id: "4",
      name: "منى أحمد",
      payedClasses: 6,
      nextPaymentDate: "2025-07-22",
      amountPaid: 600,
      remainingClasses: 2,
      postponedClasses: 2,
      canceledClasses: 0,
      absentClasses: 2,
      attendedClasses: 4,
      rate: 8,
      phoneNumber: "01233445566",
      groupName: "مجموعة 3",
    },
    {
      id: "5",
      name: "محمد سعيد",
      payedClasses: 15,
      nextPaymentDate: "2025-07-10",
      amountPaid: 1500,
      remainingClasses: 10,
      postponedClasses: 1,
      canceledClasses: 1,
      absentClasses: 3,
      attendedClasses: 5,
      rate: 2,
      phoneNumber: "01055667788",
      groupName: "مجموعة 1",
    },
    {
      id: "6",
      name: "نهى حسن",
      payedClasses: 9,
      nextPaymentDate: "2025-07-19",
      amountPaid: 900,
      remainingClasses: 4,
      postponedClasses: 0,
      canceledClasses: 0,
      absentClasses: 1,
      attendedClasses: 8,
      rate: 10,
      phoneNumber: "01099887766",
      groupName: "مجموعة 2",
    },
    {
      id: "7",
      name: "علي مصطفى",
      payedClasses: 7,
      nextPaymentDate: "2025-07-25",
      amountPaid: 700,
      remainingClasses: 3,
      postponedClasses: 1,
      canceledClasses: 0,
      absentClasses: 1,
      attendedClasses: 6,
      rate: 6,
      phoneNumber: "01111222333",
      groupName: "مجموعة 3",
    },
    {
      id: "8",
      name: "فاطمة عمر",
      payedClasses: 5,
      nextPaymentDate: "2025-07-28",
      amountPaid: 500,
      remainingClasses: 2,
      postponedClasses: 0,
      canceledClasses: 1,
      absentClasses: 2,
      attendedClasses: 3,
      rate: 4,
      phoneNumber: "01222334455",
      groupName: "مجموعة 2",
    },
    {
      id: "9",
      name: "زياد محمد",
      payedClasses: 10,
      nextPaymentDate: "2025-07-13",
      amountPaid: 1000,
      remainingClasses: 7,
      postponedClasses: 0,
      canceledClasses: 0,
      absentClasses: 1,
      attendedClasses: 9,
      rate: 10,
      phoneNumber: "01033445566",
      groupName: "مجموعة 1",
    },
    {
      id: "10",
      name: "هبة إبراهيم",
      payedClasses: 6,
      nextPaymentDate: "2025-07-17",
      amountPaid: 600,
      remainingClasses: 1,
      postponedClasses: 1,
      canceledClasses: 0,
      absentClasses: 4,
      attendedClasses: 2,
      rate: 2,
      phoneNumber: "01066778899",
      groupName: "مجموعة 3",
    },
  ]);
  const [teacherData, setTeacherData] = useState<Teacher[]>([
    {
      id: "t1",
      name: "أحمد عبد الله",
      phoneNumber: "01012345678",
      pricePerClass: 100,
      totalDueThisMonth: 800,
      totalClassesThisMonth: 10,
      completedClasses: 8,
      remainingClasses: 2,
      postponedClasses: 1,
      canceledClasses: 0,
      absentClasses: 1,
      classLink: "https://zoom.us/ahmed-abdallah",
      groups: ["القرآن", "النحو"],
    },
    {
      id: "t2",
      name: "سارة محمد",
      phoneNumber: "01087654321",
      pricePerClass: 120,
      totalDueThisMonth: 960,
      totalClassesThisMonth: 12,
      completedClasses: 8,
      remainingClasses: 4,
      postponedClasses: 2,
      canceledClasses: 1,
      absentClasses: 1,
      classLink: "https://zoom.us/sara-mohamed",
      groups: ["الفقه", "العقيدة"],
    },
    {
      id: "t3",
      name: "خالد محمود",
      phoneNumber: "01099887766",
      pricePerClass: 90,
      totalDueThisMonth: 720,
      totalClassesThisMonth: 10,
      completedClasses: 6,
      remainingClasses: 4,
      postponedClasses: 0,
      canceledClasses: 0,
      absentClasses: 0,
      classLink: "https://zoom.us/khaled-mahmoud",
      groups: ["اللغة العربية"],
    },
    {
      id: "t4",
      name: "منى السيد",
      phoneNumber: "01044556677",
      pricePerClass: 110,
      totalDueThisMonth: 990,
      totalClassesThisMonth: 11,
      completedClasses: 10,
      remainingClasses: 1,
      postponedClasses: 0,
      canceledClasses: 0,
      absentClasses: 0,
      classLink: "https://zoom.us/mona-elsayed",
      groups: ["التجويد"],
    },
    {
      id: "t5",
      name: "ياسر فتحي",
      phoneNumber: "01011223344",
      pricePerClass: 95,
      totalDueThisMonth: 855,
      totalClassesThisMonth: 9,
      completedClasses: 7,
      remainingClasses: 2,
      postponedClasses: 1,
      canceledClasses: 1,
      absentClasses: 0,
      classLink: "https://zoom.us/yasser-fathy",
      groups: ["الحديث", "السيرة"],
    },
    {
      id: "t6",
      name: "دعاء حسن",
      phoneNumber: "01099882255",
      pricePerClass: 105,
      totalDueThisMonth: 945,
      totalClassesThisMonth: 9,
      completedClasses: 9,
      remainingClasses: 0,
      postponedClasses: 0,
      canceledClasses: 0,
      absentClasses: 0,
      classLink: "https://zoom.us/doaa-hassan",
      groups: ["الفقه", "البلاغة"],
    },
    {
      id: "t7",
      name: "محمود صابر",
      phoneNumber: "01077889900",
      pricePerClass: 130,
      totalDueThisMonth: 1170,
      totalClassesThisMonth: 10,
      completedClasses: 9,
      remainingClasses: 1,
      postponedClasses: 0,
      canceledClasses: 0,
      absentClasses: 1,
      classLink: "https://zoom.us/mahmoud-saber",
      groups: ["الأدب الإسلامي"],
    },
    {
      id: "t8",
      name: "نهى إبراهيم",
      phoneNumber: "01033445566",
      pricePerClass: 100,
      totalDueThisMonth: 1000,
      totalClassesThisMonth: 10,
      completedClasses: 10,
      remainingClasses: 0,
      postponedClasses: 0,
      canceledClasses: 0,
      absentClasses: 0,
      classLink: "https://zoom.us/noha-ibrahim",
      groups: ["المستوى التمهيدي"],
    },
    {
      id: "t9",
      name: "سعيد رمضان",
      phoneNumber: "01066554433",
      pricePerClass: 85,
      totalDueThisMonth: 765,
      totalClassesThisMonth: 9,
      completedClasses: 8,
      remainingClasses: 1,
      postponedClasses: 0,
      canceledClasses: 0,
      absentClasses: 1,
      classLink: "https://zoom.us/saeed-ramadan",
      groups: ["المستوى الأول"],
    },
    {
      id: "t10",
      name: "إيمان يوسف",
      phoneNumber: "01022334455",
      pricePerClass: 115,
      totalDueThisMonth: 1035,
      totalClassesThisMonth: 9,
      completedClasses: 9,
      remainingClasses: 0,
      postponedClasses: 0,
      canceledClasses: 0,
      absentClasses: 0,
      classLink: "https://zoom.us/eman-youssef",
      groups: ["القرآن", "المحادثة"],
    },
  ]);
  const [groupData, setgroupData] = useState<Group[]>([
    {
      id: "g1",
      name: "مجموعة التأسيس",
      teacherName: "أحمد عبد الله",
      classDate: "2025-07-10 17:00",
      totalClasses: 12,
      postponedClasses: 1,
      remainingClasses: 4,
      canceledClasses: 1,
      classLink: "https://zoom.us/group1",
      students: ["خالد محمد", "أحمد سعيد", "ياسمين جمال"],
    },
    {
      id: "g2",
      name: "مجموعة النحو",
      teacherName: "سارة محمد",
      classDate: "2025-07-11 19:00",
      totalClasses: 10,
      postponedClasses: 0,
      remainingClasses: 2,
      canceledClasses: 0,
      classLink: "https://zoom.us/group2",
      students: ["فاطمة حسن", "منة سامي", "يوسف محمد"],
    },
    {
      id: "g3",
      name: "مجموعة القرآن",
      teacherName: "خالد محمود",
      classDate: "2025-07-09 16:00",
      totalClasses: 14,
      postponedClasses: 2,
      remainingClasses: 5,
      canceledClasses: 1,
      classLink: "https://zoom.us/group3",
      students: ["علي رضا", "هبة الله", "شيماء عبد السلام"],
    },
    {
      id: "g4",
      name: "مجموعة الفقه",
      teacherName: "منى السيد",
      classDate: "2025-07-13 18:00",
      totalClasses: 8,
      postponedClasses: 0,
      remainingClasses: 1,
      canceledClasses: 0,
      classLink: "https://zoom.us/group4",
      students: ["سعد رمضان", "نور أحمد", "إيمان علاء"],
    },
    {
      id: "g5",
      name: "مجموعة العقيدة",
      teacherName: "ياسر فتحي",
      classDate: "2025-07-14 17:30",
      totalClasses: 10,
      postponedClasses: 1,
      remainingClasses: 3,
      canceledClasses: 0,
      classLink: "https://zoom.us/group5",
      students: ["محمود زكي", "زينب عماد", "عبد الرحمن خالد"],
    },
    {
      id: "g6",
      name: "مجموعة التفسير",
      teacherName: "دعاء حسن",
      classDate: "2025-07-10 20:00",
      totalClasses: 12,
      postponedClasses: 2,
      remainingClasses: 2,
      canceledClasses: 2,
      classLink: "https://zoom.us/group6",
      students: ["ملك أحمد", "سلمى خالد", "آدم مصطفى"],
    },
    {
      id: "g7",
      name: "مجموعة البلاغة",
      teacherName: "محمود صابر",
      classDate: "2025-07-15 17:00",
      totalClasses: 9,
      postponedClasses: 0,
      remainingClasses: 4,
      canceledClasses: 0,
      classLink: "https://zoom.us/group7",
      students: ["أميرة عبد الله", "مصطفى علوي", "جنى محمود"],
    },
    {
      id: "g8",
      name: "مجموعة المستوى الأول",
      teacherName: "نهى إبراهيم",
      classDate: "2025-07-12 16:30",
      totalClasses: 11,
      postponedClasses: 1,
      remainingClasses: 1,
      canceledClasses: 1,
      classLink: "https://zoom.us/group8",
      students: ["أنس عبد الرحيم", "رهف حمدي", "آية تامر"],
    },
    {
      id: "g9",
      name: "مجموعة الحديث",
      teacherName: "سعيد رمضان",
      classDate: "2025-07-09 19:00",
      totalClasses: 10,
      postponedClasses: 0,
      remainingClasses: 2,
      canceledClasses: 0,
      classLink: "https://zoom.us/group9",
      students: ["عبد الله حسام", "سارة منير", "ليلى أشرف"],
    },
    {
      id: "g10",
      name: "مجموعة المحادثة",
      teacherName: "إيمان يوسف",
      classDate: "2025-07-08 18:00",
      totalClasses: 9,
      postponedClasses: 1,
      remainingClasses: 2,
      canceledClasses: 0,
      classLink: "https://zoom.us/group10",
      students: ["زين محمد", "حبيبة عمرو", "جاسر عمر"],
    },
  ]);

  const [activeTab, setActiveTab] = useState("overview");

  const renderActiveComponent = () => {
    switch (activeTab) {
      case "overview":
        return <DashboardOverview />;
      case "users":
        return (
          <UserManagement
            studentData={studentData}
            teacherData={teacherData}
            groupData={groupData}
          />
        );
      case "courses":
        return <LessonManagement />;
      case "financial":
        return <FinancialOverview />;
      default:
        return <DashboardOverview />;
    }
  };

  return (
    <AdminLayout activeTab={activeTab} setActiveTab={setActiveTab}>
      <div className={styles.dashboardContent}>{renderActiveComponent()}</div>
    </AdminLayout>
  );
};

export default AdminDashboard;
