"use client";
import { useState } from "react";
import UserManagement from "@/components/dashboard/admin/sections/UserManagement/UserManagement";
import styles from "@/styles/AdminDashboard.module.css";
import { Student } from "@/utils/types";

export default function UserManagementPage() {
  const [studentData] = useState<Student[]>([
    {
      id: "1",
      name: "أحمد محمد",
      payedClasses: 10,
      nextPaymentDate: "2025-07-15",
      amountPaid: 1000,
      remainingClasses: 4,
      postponedClasses: 2,
      canceledClasses: 1,
      absentClasses: 3,
      attendedClasses: 6,
      rate: 10,
      phoneNumber: "01012345678",
      groupName: "مجموعة 1",
    },
    {
      id: "2",
      name: "سارة علي",
      payedClasses: 8,
      nextPaymentDate: "2025-07-20",
      amountPaid: 800,
      remainingClasses: 6,
      postponedClasses: 1,
      canceledClasses: 0,
      absentClasses: 2,
      attendedClasses: 5,
      rate: 9,
      phoneNumber: "01087654321",
      groupName: "مجموعة 2",
    },
    {
      id: "3",
      name: "محمد حسن",
      payedClasses: 12,
      nextPaymentDate: "2025-07-25",
      amountPaid: 1200,
      remainingClasses: 8,
      postponedClasses: 3,
      canceledClasses: 2,
      absentClasses: 1,
      attendedClasses: 8,
      rate: 8,
      phoneNumber: "01123456789",
      groupName: "مجموعة 3",
    },
    {
      id: "4",
      name: "فاطمة خالد",
      payedClasses: 6,
      nextPaymentDate: "2025-07-30",
      amountPaid: 600,
      remainingClasses: 3,
      postponedClasses: 0,
      canceledClasses: 1,
      absentClasses: 2,
      attendedClasses: 3,
      rate: 7,
      phoneNumber: "01198765432",
      groupName: "مجموعة 1",
    },
    {
      id: "5",
      name: "عبد الله أحمد",
      payedClasses: 15,
      nextPaymentDate: "2025-08-05",
      amountPaid: 1500,
      remainingClasses: 10,
      postponedClasses: 1,
      canceledClasses: 0,
      absentClasses: 4,
      attendedClasses: 10,
      rate: 10,
      phoneNumber: "01234567890",
      groupName: "مجموعة 2",
    },
  ]);

  const [teacherData] = useState<any[]>([
    {
      id: "t1",
      name: "أحمد عبد الله",
      qualifications: "ماجستير في الشريعة الإسلامية",
      rate: 9.5,
      totalHours: 120,
      completedHours: 100,
      totalEarnings: 10000,
      phoneNumber: "01011111111",
      email: "ahmed.abdullah@example.com",
      assignedGroups: ["مجموعة التأسيس", "مجموعة المبتدئين"],
      joiningDate: "2023-01-15",
      status: "نشط",
      specialization: "القرآن الكريم",
      experience: "10 سنوات",
      lastLoginDate: "2025-07-25",
      totalStudents: 25,
      monthlyEarnings: 2500,
    },
    {
      id: "t2",
      name: "سارة محمد",
      qualifications: "بكالوريوس في اللغة العربية",
      rate: 9.2,
      totalHours: 100,
      completedHours: 80,
      totalEarnings: 8000,
      phoneNumber: "01022222222",
      email: "sara.mohamed@example.com",
      assignedGroups: ["مجموعة النحو", "مجموعة الصرف"],
      joiningDate: "2023-03-20",
      status: "نشط",
      specialization: "النحو والصرف",
      experience: "8 سنوات",
      lastLoginDate: "2025-07-23",
      totalStudents: 20,
      monthlyEarnings: 2000,
    },
    {
      id: "t3",
      name: "خالد محمود",
      qualifications: "إجازة في القرآن الكريم",
      rate: 9.8,
      totalHours: 150,
      completedHours: 120,
      totalEarnings: 12000,
      phoneNumber: "01033333333",
      email: "khalid.mahmoud@example.com",
      assignedGroups: ["مجموعة القرآن", "مجموعة التجويد"],
      joiningDate: "2023-09-10",
      status: "نشط",
      specialization: "علوم القرآن",
      experience: "15 سنة",
      lastLoginDate: "2025-07-24",
      totalStudents: 30,
      monthlyEarnings: 3000,
    },
  ]);

  return (
    <div className={styles.dashboardContent}>
      <UserManagement studentData={studentData} teacherData={teacherData} />
    </div>
  );
}
